apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-scripts
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS biostar;
    CREATE USER IF NOT EXISTS 'biostar'@'%' IDENTIFIED BY 'biostar';
    GRANT ALL PRIVILEGES ON biostar.* TO 'biostar'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-env
              key: MYSQL_ROOT_PASSWORD  # El nombre de la clave en el Secret
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: mariadb-init
        - mountPath: /var/lib/mysql
          name: mariadb-data
        ports:
        - containerPort: 3306
      volumes:
      - name: mariadb-init
        configMap:
          name: mariadb-init-scripts  # O el nombre de tu ConfigMap si estás usando uno para inicializar
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc  # El nombre de tu PVC (PersistentVolumeClaim) para el almacenamiento persistente
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # para permitir que otros servicios se conecten al puerto

