apiVersion: v1
kind: ConfigMap
metadata:
  name: oraculo-l0-config
data:
  #MARIADB_HOST: "mariadb.devops-gyt.svc.cluster.local"
  #MARIADB_PORT: "3306"
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 0.0.0.0 [::1]"
  SITE_NAME: "Oraculo L0"
  MYSQL_DATABASE: biostar
  MYSQL_USER: biostar
  MYSQL_PASSWORD: biostar
  MYSQL_HOST: "mariadb.devops-gyt.svc.cluster.local"
  MYSQL_PORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraculo-l0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oraculo-l0
  template:
    metadata:
      labels:
        app: oraculo-l0
    spec:
      containers:
      - name: oraculo-l0
        image: oraculo_l0 # Debes construir y subir la imagen o usar una imagen existente
        imagePullPolicy: Never
        command:
        - bash
        - -c
        - "python manage.py makemigrations --settings biostar.forum.settings && python manage.py migrate --settings biostar.forum.settings && python manage.py runserver 0.0.0.0:8000 --settings biostar.forum.settings"
        envFrom:
        - secretRef:
            name: oraculo-l0-env
        - configMapRef:
            name: oraculo-l0-config
      #   volumeMounts:
      #   - mountPath: /code
      #     name: code-volume
      #   ports:
      #   - containerPort: 8000
      # volumes:
      # - name: code-volume
      #   hostPath:
      #     path: /code
      #     type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: oraculo-l0
spec:
  selector:
    app: oraculo-l0
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
