# Generated by Django 3.1 on 2021-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_tags',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_tags',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
