# Generated by Django 3.1 on 2021-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.TextField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='uid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
